repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: dotnet-format
        name: dotnet-format
        language: system
        entry: dotnet format
        files: \.(cs|csproj|sln)$
        pass_filenames: false

      - id: ruff-check
        name: ruff-check
        language: system
        entry: ruff check --fix
        types: [python]
        files: ^plugins/

      - id: ruff-format
        name: ruff-format
        language: system
        entry: ruff format
        types: [python]
        files: ^plugins/
